### ISSUE TITLE
Write more in README.md

### ISSUE THREAD

**Issue by magnusstubman** [skepticfx/fuzzcat#3]
- What exactly can it fuzz?
- How does it work?
- Usage?
- How to contribute?

**Comment by skepticfx** [comment]
Hello @magnusstubman,

Thanks for pointing out. Docs were really lacking when I wrote this long time ago. I've added more details about the usage and stuff to the Readme. Do take a look at it.

This was written initially do do easy fuzzing of network protocols using node. Then I added a feature which most fuzzers lack (SSL support with Client certificates). I wish I could spend more time on this. 

If you're interested in this project, do let me know and I can add you as a moderator and we could hack on some cool stuff. 

Does the current readme answer what you initially asked me?

**Comment by magnusstubman** [comment]
:+1:
